#!/bin/sh

set -e

echo "BAMBOO_AGENT_VERSION: $AGENT_VERSION"
echo "BAMBOO_SERVER_HOST:   $BAMBOO_SERVER_HOST"
echo "BAMBOO_SERVER_PORT:   $BAMBOO_SERVER_PORT"

CONNECTION_STRING="http://${BAMBOO_SERVER_HOST}:${BAMBOO_SERVER_PORT}/agentServer/"
AGENT_URL="http://${BAMBOO_SERVER_HOST}:${BAMBOO_SERVER_PORT}/agentServer/agentInstaller/"
AGENT_INSTALLER_FILENAME="atlassian-bamboo-agent-installer-${AGENT_VERSION}.jar"

wget -cv $AGENT_URL -O $AGENT_INSTALLER_FILENAME

echo "-> Starting Bamboo Agent."
java -jar $AGENT_INSTALLER_FILENAME $CONNECTION_STRING
 
